services:
  app:
    env_file: .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - taskiq_worker
    command: alembic upgrade head && uvicorn src.core.app:app --reload --host ${APP_HOST} --port ${APP_PORT}


  postgresql:

    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/postgresql:/var/log/postgresql
    env_file: .env
    restart: always


  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  taskiq_worker:
    build: .
    env_file: .env
    depends_on:
      - rabbitmq
    command: taskiq worker src.core.taskiq_app:broker --fs-discover --tasks-pattern **/tasks/*.py

networks:
  flower_shop_net:
    driver: bridge

volumes:
  rabbitmq-data:
  taskiq:
  redis-data:
  postgres_data:
