services:
  app:
    env_file: .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - taskiq_worker
      - postgres
    command: bash -c "alembic upgrade head && python main.py"
    restart: always
    networks: [ backend_net ]


  postgres:
    image: postgres:16
    env_file: [ .env ]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports: [ "5432:5432" ]
    restart: always
    networks: [ backend_net ]

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: [ backend_net ]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    networks: [ backend_net ]

  taskiq_worker:
    build: .
    env_file: .env
    depends_on:
      - rabbitmq
    command: taskiq worker src.core.taskiq_app:broker --fs-discover --tasks-pattern **/tasks/*.py
    networks: [ backend_net ]

  nginx:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
    image: nginx:stable
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.init.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    networks: [ backend_net ]

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    env_file: [ .env ]
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot -d ${APP_DOMAIN} \
      --email ${APP_DEVELOPER_EMAIL} --agree-tos --no-eff-email --non-interactive && echo 'CERT DONE'"
    networks: [ backend_net ]

networks:
  backend_net:
    driver: bridge

volumes:
  rabbitmq-data:
  taskiq:
  redis-data:
  postgres_data:
  certbot_www:
  certbot_etc:
