"""comments model

Revision ID: 0e0c319511d0
Revises: 7074effe7e7c
Create Date: 2026-04-12 17:16:08.779838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0c319511d0'
down_revision: Union[str, Sequence[str], None] = '7074effe7e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('comments',
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(length=250), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        # with op.batch_alter_table('game_images', schema=None) as batch_op:
        #     batch_op.create_unique_constraint(None, ['image'])

        # ### end Alembic commands ###
    except:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('comments')
    # ### end Alembic commands ###
