"""verify_email

Revision ID: 11d2138f7c63
Revises: 7dfca14bab50
Create Date: 2026-04-04 17:08:35.847522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d2138f7c63'
down_revision: Union[str, Sequence[str], None] = '7dfca14bab50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verify_email', sa.Boolean(), nullable=False))
    op.alter_column('users', 'is_verify_otp',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verify_otp',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'is_verify_email')
    # ### end Alembic commands ###
