"""otp secret user

Revision ID: 4ce125d4edc3
Revises: 95d1228f5517
Create Date: 2026-04-19 13:03:02.580179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce125d4edc3'
down_revision: Union[str, Sequence[str], None] = '95d1228f5517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    try:
        with op.batch_alter_table('game_images', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='unique')
    except:
        pass

    # ### end Alembic commands ###
