"""game id

Revision ID: 5f6dd679d20a
Revises: 85ddc77812ab
Create Date: 2026-04-10 10:19:01.750960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6dd679d20a'
down_revision: Union[str, Sequence[str], None] = '85ddc77812ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'torrents', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'torrents', type_='foreignkey')
    op.drop_column('torrents', 'game_id')
    # ### end Alembic commands ###
