"""username unique

Revision ID: 7d314fdf39c0
Revises: b739ce1ca48f
Create Date: 2026-04-20 15:53:13.210912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d314fdf39c0'
down_revision: Union[str, Sequence[str], None] = 'b739ce1ca48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('game_images', schema=None) as batch_op:
            batch_op.create_unique_constraint(None, ['image'])
    except:
        pass

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    try:
        with op.batch_alter_table('game_images', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='unique')
    except:
        pass

    # ### end Alembic commands ###
