"""avatar image user

Revision ID: 7dfca14bab50
Revises: ee181e030f90
Create Date: 2026-04-04 13:01:51.109840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfca14bab50'
down_revision: Union[str, Sequence[str], None] = 'ee181e030f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_image', sa.String(), nullable=True))
    op.alter_column('users', 'is_verify_otp',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verify_otp',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'avatar_image')
    # ### end Alembic commands ###
