"""tags table

Revision ID: 95d1228f5517
Revises: 0e0c319511d0
Create Date: 2026-04-15 17:02:15.601610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d1228f5517'
down_revision: Union[str, Sequence[str], None] = '0e0c319511d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    try:
        op.create_table('game_tags',
                        sa.Column('game_id', sa.Integer(), nullable=False),
                        sa.Column('name', sa.String(), nullable=False),
                        sa.Column('image', sa.String(), nullable=True),
                        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                        sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
                        sa.PrimaryKeyConstraint('id')
                        )

        # ### end Alembic commands ###
    except:
        pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('game_tags')
    # ### end Alembic commands ###
