"""is otp verify

Revision ID: ee181e030f90
Revises: aa6bdbb19646
Create Date: 2026-04-01 09:53:11.327358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee181e030f90'
down_revision: Union[str, Sequence[str], None] = 'aa6bdbb19646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verify_otp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verify_otp')
    # ### end Alembic commands ###
